# Generated by Django 5.2 on 2025-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='O', max_length=1),
        ),
    ]
