# Generated by Django 5.2 on 2025-05-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0002_alter_crianca_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apadrinhamento',
            old_name='crianca',
            new_name='apadrinhado',
        ),
    ]
