# Generated by Django 5.2 on 2025-05-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0003_rename_crianca_apadrinhamento_apadrinhado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apadrinhamento',
            old_name='apadrinhado',
            new_name='crianca',
        ),
    ]
